route:
  group_by: [ alertname ]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'mail'

receivers:
  - name: 'mail'
    email_configs:
      - smarthost: '****'
        auth_username: '****'
        auth_identity: '****'
        auth_password: '****'
        from: '****'
        to: '****'
        send_resolved: true

