groups:
  - name: Alerts
    rules:
      - alert: InstanceDownCritical
        expr: up{job="python_demo_staging"} < 1 
        for: 1m 
        labels:
          severity: high
        annotations:
          summary: 'Alert with high severity.'
